Repository onflow/CAST, pull requests merged in 2023-09, with the labels that each got.

#8 Footer textual changes
  frontend/packages/client/public/Footer-heart.png
  frontend/packages/client/src/components/HomeFooter.js
Labels: enhancement, good first issue

#16 Flips Default Image.
  frontend/packages/client/src/assets/Flip_Default.png
  frontend/packages/client/src/components/FlipsContainer/FlipCardBody.js
Labels: enhancement, phase-0

#10 Community Creation Automation
  frontend/packages/client/src/components/Community/ProposalThresholdEditor/FormConfig.js
  frontend/packages/client/src/components/Community/ProposalThresholdEditor/ProposalThresholdEditor.js
  frontend/packages/client/src/components/Community/ProposalThresholdEditor/ThresholdForm.js
  frontend/packages/client/src/components/Community/StrategyEditorModal/StrategyInformationForm.js
  frontend/packages/client/src/components/Community/StrategySelectorForm.js
  frontend/packages/client/src/components/CommunityCreate/StepThree.js
  frontend/packages/client/src/components/common/Dropdown.js
  frontend/packages/client/src/components/common/Input.js
  frontend/packages/client/src/data/contractsAndPaths.json
  frontend/packages/client/src/data/dataServices.js
Labels: enhancement, phase-0

#15 Bug fix for one-address-one-vote strategy
  frontend/packages/client/src/networks.js
Labels: bug, phase-0

#18 Flip cards height fixes and textual changres
  frontend/packages/client/src/components/FlipsContainer/FlipCardBody.js
  frontend/packages/client/src/components/FlipsContainer/FlipCardHeader.js
  frontend/packages/client/src/components/FlipsContainer/FlipsCard.js
  frontend/packages/client/src/components/FlipsContainer/index.js
  frontend/packages/client/src/components/FlipsContainer/index.module.scss
  frontend/packages/client/src/components/HomeHeader.js
Labels: bug, phase-0

#19 Update links to point to new subdomain
  frontend/packages/client/src/components/Community/ProposalThresholdEditor/ThresholdForm.js
  frontend/packages/client/src/components/Community/StrategyEditorModal/StrategyInformationForm.js
  frontend/packages/client/src/components/TooltipMessage.js
Labels: good first issue
